# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module HealthOs
  class AllFoodBrandsResponse < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :brand_name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :food_brand_id

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["brand_name"] = "brand_name"
        @hash["food_brand_id"] = "food_brand_id"
      end
      @hash
    end

    def initialize(brand_name = nil,
                   food_brand_id = nil)
      @brand_name = brand_name
      @food_brand_id = food_brand_id
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        brand_name = hash["brand_name"]
        food_brand_id = hash["food_brand_id"]

        # Create object from extracted values
        AllFoodBrandsResponse.new(brand_name,
                                  food_brand_id)
      end
    end
  end
end
