# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module HealthOs
  class AllGenericsResponse < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :pregnancy_category

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :lactation_category

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :instructions

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :faqs

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :genric_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :side_effects

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :how_it_works

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :therapeutic_class

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :used_for

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :strength

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :schedule

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :alcohol_interaction_description

    # TODO: Write general description for this method
    # @return [Boolean]
    attr_accessor :alcohol_nteraction

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["name"] = "name"
        @hash["pregnancy_category"] = "pregnancy_category"
        @hash["lactation_category"] = "lactation_category"
        @hash["instructions"] = "instructions"
        @hash["faqs"] = "faqs"
        @hash["genric_id"] = "genric_id"
        @hash["side_effects"] = "side_effects"
        @hash["how_it_works"] = "how_it_works"
        @hash["therapeutic_class"] = "therapeutic_class"
        @hash["used_for"] = "used_for"
        @hash["strength"] = "strength"
        @hash["schedule"] = "schedule"
        @hash["alcohol_interaction_description"] = "alcohol_interaction_description"
        @hash["alcohol_nteraction"] = "alcohol_nteraction"
      end
      @hash
    end

    def initialize(name = nil,
                   pregnancy_category = nil,
                   lactation_category = nil,
                   instructions = nil,
                   faqs = nil,
                   genric_id = nil,
                   side_effects = nil,
                   how_it_works = nil,
                   therapeutic_class = nil,
                   used_for = nil,
                   strength = nil,
                   schedule = nil,
                   alcohol_interaction_description = nil,
                   alcohol_nteraction = nil)
      @name = name
      @pregnancy_category = pregnancy_category
      @lactation_category = lactation_category
      @instructions = instructions
      @faqs = faqs
      @genric_id = genric_id
      @side_effects = side_effects
      @how_it_works = how_it_works
      @therapeutic_class = therapeutic_class
      @used_for = used_for
      @strength = strength
      @schedule = schedule
      @alcohol_interaction_description = alcohol_interaction_description
      @alcohol_nteraction = alcohol_nteraction
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        name = hash["name"]
        pregnancy_category = hash["pregnancy_category"]
        lactation_category = hash["lactation_category"]
        instructions = hash["instructions"]
        faqs = hash["faqs"]
        genric_id = hash["genric_id"]
        side_effects = hash["side_effects"]
        how_it_works = hash["how_it_works"]
        therapeutic_class = hash["therapeutic_class"]
        used_for = hash["used_for"]
        strength = hash["strength"]
        schedule = hash["schedule"]
        alcohol_interaction_description = hash["alcohol_interaction_description"]
        alcohol_nteraction = hash["alcohol_nteraction"]

        # Create object from extracted values
        AllGenericsResponse.new(name,
                                pregnancy_category,
                                lactation_category,
                                instructions,
                                faqs,
                                genric_id,
                                side_effects,
                                how_it_works,
                                therapeutic_class,
                                used_for,
                                strength,
                                schedule,
                                alcohol_interaction_description,
                                alcohol_nteraction)
      end
    end
  end
end
