# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module HealthOs
  class AllExercisesResponse < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :calory_count

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :category

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :cardio_subcategory

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :primary_muscle_group

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :excercise_id

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["name"] = "name"
        @hash["calory_count"] = "calory_count"
        @hash["category"] = "category"
        @hash["cardio_subcategory"] = "cardio_subcategory"
        @hash["primary_muscle_group"] = "primary_muscle_group"
        @hash["excercise_id"] = "excercise_id"
      end
      @hash
    end

    def initialize(name = nil,
                   calory_count = nil,
                   category = nil,
                   cardio_subcategory = nil,
                   primary_muscle_group = nil,
                   excercise_id = nil)
      @name = name
      @calory_count = calory_count
      @category = category
      @cardio_subcategory = cardio_subcategory
      @primary_muscle_group = primary_muscle_group
      @excercise_id = excercise_id
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        name = hash["name"]
        calory_count = hash["calory_count"]
        category = hash["category"]
        cardio_subcategory = hash["cardio_subcategory"]
        primary_muscle_group = hash["primary_muscle_group"]
        excercise_id = hash["excercise_id"]

        # Create object from extracted values
        AllExercisesResponse.new(name,
                                 calory_count,
                                 category,
                                 cardio_subcategory,
                                 primary_muscle_group,
                                 excercise_id)
      end
    end
  end
end
