# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module HealthOs
  class AllLabTestsResponse < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :lab_test_name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :alternate_name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :lab_test_id

    # TODO: Write general description for this method
    # @return [LabTestData34]
    attr_accessor :lab_test_data

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["lab_test_name"] = "lab_test_name"
        @hash["alternate_name"] = "alternate_name"
        @hash["lab_test_id"] = "lab_test_id"
        @hash["lab_test_data"] = "lab_test_data"
      end
      @hash
    end

    def initialize(lab_test_name = nil,
                   alternate_name = nil,
                   lab_test_id = nil,
                   lab_test_data = nil)
      @lab_test_name = lab_test_name
      @alternate_name = alternate_name
      @lab_test_id = lab_test_id
      @lab_test_data = lab_test_data
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        lab_test_name = hash["lab_test_name"]
        alternate_name = hash["alternate_name"]
        lab_test_id = hash["lab_test_id"]
        lab_test_data = LabTestData34.from_hash(hash["lab_test_data"]) if hash["lab_test_data"]

        # Create object from extracted values
        AllLabTestsResponse.new(lab_test_name,
                                alternate_name,
                                lab_test_id,
                                lab_test_data)
      end
    end
  end
end
