# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module HealthOs
  class CommonSideEffectsResponse < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :generic

    # TODO: Write general description for this method
    # @return [List of SideEffect]
    attr_accessor :side_effects

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["generic"] = "generic"
        @hash["side_effects"] = "side_effects"
      end
      @hash
    end

    def initialize(generic = nil,
                   side_effects = nil)
      @generic = generic
      @side_effects = side_effects
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        generic = hash["generic"]
        # Parameter is an array, so we need to iterate through it
        side_effects = nil
        if hash["side_effects"] != nil
          side_effects = Array.new
          hash["side_effects"].each{|structure| side_effects << (SideEffect.from_hash(structure) if structure)}
        end

        # Create object from extracted values
        CommonSideEffectsResponse.new(generic,
                                      side_effects)
      end
    end
  end
end
