# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module HealthOs
  class Constituent < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :strength

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["name"] = "name"
        @hash["strength"] = "strength"
      end
      @hash
    end

    def initialize(name = nil,
                   strength = nil)
      @name = name
      @strength = strength
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        name = hash["name"]
        strength = hash["strength"]

        # Create object from extracted values
        Constituent.new(name,
                        strength)
      end
    end
  end
end
