# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module HealthOs
  class GenericsResponse < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :name

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :generic_id

    # TODO: Write general description for this method
    # @return [List of String]
    attr_accessor :therauptic_uses

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :search_score

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["name"] = "name"
        @hash["generic_id"] = "generic_id"
        @hash["therauptic_uses"] = "therauptic_uses"
        @hash["search_score"] = "search_score"
      end
      @hash
    end

    def initialize(name = nil,
                   generic_id = nil,
                   therauptic_uses = nil,
                   search_score = nil)
      @name = name
      @generic_id = generic_id
      @therauptic_uses = therauptic_uses
      @search_score = search_score
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        name = hash["name"]
        generic_id = hash["generic_id"]
        therauptic_uses = hash["therauptic_uses"]
        search_score = hash["search_score"]

        # Create object from extracted values
        GenericsResponse.new(name,
                             generic_id,
                             therauptic_uses,
                             search_score)
      end
    end
  end
end
