# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module HealthOs
  class Interaction < BaseModel
    # TODO: Write general description for this method
    # @return [List of Item]
    attr_accessor :items

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :severity

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :description

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :source

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["items"] = "items"
        @hash["severity"] = "severity"
        @hash["description"] = "description"
        @hash["source"] = "source"
      end
      @hash
    end

    def initialize(items = nil,
                   severity = nil,
                   description = nil,
                   source = nil)
      @items = items
      @severity = severity
      @description = description
      @source = source
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        # Parameter is an array, so we need to iterate through it
        items = nil
        if hash["items"] != nil
          items = Array.new
          hash["items"].each{|structure| items << (Item.from_hash(structure) if structure)}
        end
        severity = hash["severity"]
        description = hash["description"]
        source = hash["source"]

        # Create object from extracted values
        Interaction.new(items,
                        severity,
                        description,
                        source)
      end
    end
  end
end
