# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module HealthOs
  class Item < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :name

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["name"] = "name"
      end
      @hash
    end

    def initialize(name = nil)
      @name = name
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        name = hash["name"]

        # Create object from extracted values
        Item.new(name)
      end
    end
  end
end
