# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module HealthOs
  class LabTestData < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :ordering_information

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :alternate_names

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :laboratory

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :test_code

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :specimen_types

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :container_types

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :minimum_adult_volume

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :frequency

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :external_laboratory

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["ordering_information"] = "Ordering information"
        @hash["alternate_names"] = "Alternate names"
        @hash["laboratory"] = "Laboratory"
        @hash["test_code"] = "Test Code"
        @hash["specimen_types"] = "Specimen types"
        @hash["container_types"] = "Container types"
        @hash["minimum_adult_volume"] = "Minimum Adult Volume"
        @hash["frequency"] = "Frequency"
        @hash["external_laboratory"] = "External Laboratory"
      end
      @hash
    end

    def initialize(ordering_information = nil,
                   alternate_names = nil,
                   laboratory = nil,
                   test_code = nil,
                   specimen_types = nil,
                   container_types = nil,
                   minimum_adult_volume = nil,
                   frequency = nil,
                   external_laboratory = nil)
      @ordering_information = ordering_information
      @alternate_names = alternate_names
      @laboratory = laboratory
      @test_code = test_code
      @specimen_types = specimen_types
      @container_types = container_types
      @minimum_adult_volume = minimum_adult_volume
      @frequency = frequency
      @external_laboratory = external_laboratory
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        ordering_information = hash["Ordering information"]
        alternate_names = hash["Alternate names"]
        laboratory = hash["Laboratory"]
        test_code = hash["Test Code"]
        specimen_types = hash["Specimen types"]
        container_types = hash["Container types"]
        minimum_adult_volume = hash["Minimum Adult Volume"]
        frequency = hash["Frequency"]
        external_laboratory = hash["External Laboratory"]

        # Create object from extracted values
        LabTestData.new(ordering_information,
                        alternate_names,
                        laboratory,
                        test_code,
                        specimen_types,
                        container_types,
                        minimum_adult_volume,
                        frequency,
                        external_laboratory)
      end
    end
  end
end
