# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module HealthOs
  class MedicineInteractionsResponse < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :generic

    # TODO: Write general description for this method
    # @return [List of Interaction]
    attr_accessor :interactions

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["generic"] = "generic"
        @hash["interactions"] = "interactions"
      end
      @hash
    end

    def initialize(generic = nil,
                   interactions = nil)
      @generic = generic
      @interactions = interactions
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        generic = hash["generic"]
        # Parameter is an array, so we need to iterate through it
        interactions = nil
        if hash["interactions"] != nil
          interactions = Array.new
          hash["interactions"].each{|structure| interactions << (Interaction.from_hash(structure) if structure)}
        end

        # Create object from extracted values
        MedicineInteractionsResponse.new(generic,
                                         interactions)
      end
    end
  end
end
