# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module HealthOs
  class PopularUsageResponse < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :generic

    # TODO: Write general description for this method
    # @return [List of Usage]
    attr_accessor :usages

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["generic"] = "generic"
        @hash["usages"] = "usages"
      end
      @hash
    end

    def initialize(generic = nil,
                   usages = nil)
      @generic = generic
      @usages = usages
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        generic = hash["generic"]
        # Parameter is an array, so we need to iterate through it
        usages = nil
        if hash["usages"] != nil
          usages = Array.new
          hash["usages"].each{|structure| usages << (Usage.from_hash(structure) if structure)}
        end

        # Create object from extracted values
        PopularUsageResponse.new(generic,
                                 usages)
      end
    end
  end
end
