# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module HealthOs
  class RequestAccessTokenRequest < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :grant_type

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :client_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :client_secret

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :scope

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["grant_type"] = "grant_type"
        @hash["client_id"] = "client_id"
        @hash["client_secret"] = "client_secret"
        @hash["scope"] = "scope"
      end
      @hash
    end

    def initialize(grant_type = nil,
                   client_id = nil,
                   client_secret = nil,
                   scope = nil)
      @grant_type = grant_type
      @client_id = client_id
      @client_secret = client_secret
      @scope = scope
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        grant_type = hash["grant_type"]
        client_id = hash["client_id"]
        client_secret = hash["client_secret"]
        scope = hash["scope"]

        # Create object from extracted values
        RequestAccessTokenRequest.new(grant_type,
                                      client_id,
                                      client_secret,
                                      scope)
      end
    end
  end
end
