# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module HealthOs
  class Schedule < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :category

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :label

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["category"] = "category"
        @hash["label"] = "label"
      end
      @hash
    end

    def initialize(category = nil,
                   label = nil)
      @category = category
      @label = label
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        category = hash["category"]
        label = hash["label"]

        # Create object from extracted values
        Schedule.new(category,
                     label)
      end
    end
  end
end
