# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module HealthOs
  class SideEffect < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :term

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :count

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :percent

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["term"] = "term"
        @hash["count"] = "count"
        @hash["percent"] = "percent"
      end
      @hash
    end

    def initialize(term = nil,
                   count = nil,
                   percent = nil)
      @term = term
      @count = count
      @percent = percent
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        term = hash["term"]
        count = hash["count"]
        percent = hash["percent"]

        # Create object from extracted values
        SideEffect.new(term,
                       count,
                       percent)
      end
    end
  end
end
